- migrations/20220628002205-create-entries.js
- models/entries.js
COMO: usuario administrador
QUIERO: gestionar las Novedades
PARA: administrar el contenido
Criterios de aceptación: Las entradas serán el contenido publicado en la sección "Novedades" del sitio. Nombre de tabla: entries. Campos: name, content, image, categoryId, type (una entrada podrá ser event, news, etc), deletedAt (utilizado para softDelete)
> OT222-40 Migracion y modelo de novedades

- controllers/user.controllers.js
- routes/users.js
COMO: usuario administrador
QUIERO: visualizar un listado de Usuarios
PARA: mantener un seguimiento de quiénes forman parte del sistema
Criterios de aceptación: GET a /users . Devolverá un listado de todos los Usuarios. Este endpoint solo deberá ser accesible por los Usuarios administradores.
Faltaria agregar el middleware que valida usuarios administradores
> endpoint get usuarios

- app.js
- controllers/news.controllers.js
- package-lock.json
- package.json
- routes/news.js
- validations/newValidationSchema.js
- validations/userValidationSchema.js
- yarn.lock
* Endpoint /new for create a new
* New validation schema
> OT222-55 endpoint POST /news

- app.js
- routes/news.js
/news GET endpoint created on a new router file and added to app.js.
> Ot222-45 - /news GET endpoint

- app.js
- controllers/news.controllers.js
- package-lock.json
- package.json
- routes/news.js
- validations/newValidationSchema.js
- validations/userValidationSchema.js
- yarn.lock
* Endpoint PUT: '/news/:id' created
> Ot222 56 Endpont PUT: '/news/:id'

- app.js
- controllers/contacts.js
- routes/contacts.js
El modelo no existe todavia por lo que esta comentado.
COMO usuario
QUIERO listar los Contactos de la página
PARA poder ver todos los que existen
Criterios de aceptación:
GET /contacts - Devolverá todos los registros de Contactos. Este endpoint solo podrá ser accedido por un usuario administrador
> endpoint get contactos

- migrations/20220628224907-create-activities.js
- seeders/20220706025510-demo-activities.js
Seeder for activities created.
10 seeds total.
activities.content datatype changed from `STRING` to `TEXT` to allow longer contents.
> Ot222 69 - Activities seeder

- controllers/testimonials.js
- routes/middlewares/ValidateTestimonialId.js
- routes/testimonials.js
COMO usuario administrador
QUIERO actualizar los Testimonios
PARA informar nuevas Novedades acerca de la ONG.
Criterios de aceptación:
PUT /testimonials/:id - Deberá validar que la novedad exista en base al id enviado por parámetro. En el caso de que no exista, deberá devolver un error, mientras que en caso contrario, deberá actualizarla y devolverla con los datos nuevos.
> OT222-85-endpoint put testimonials

- controllers/auth.controllers.js
- routes/news.js
Agregue que devolviera el campo del roleId en la función authME para poder determinar si el usuario es administrador o no
> agregue roleId en authme

- controllers/organizations.js
- migrations/20220709181610-create-organization.js
- models/organization.js
- seeders/20220709181734-demo-organization.js
creación de Modelo, seeds y modificación de endpoint GET de datos públicos
> creación de Modelo, Seeds y Modificación de endpoint de Datos Públicos

- controllers/contacts.js
- migrations/20220709184349-create-contact.js
- models/contact.js
- routes/middlewares/validateContactsFields.js
- seeders/20201109013159-create-demo-user.js
- seeders/20220709184506-demo-contact.js
hice el get y el delete para la tarjeta 76 y el modelo, migración y seeds de contacto para poder avanzar con mis tarjetas
COMO: Desarrollador
QUIERO: Enviar los datos del Formulario de Contacto a la API 
PARA: Almacenarlos en la base de datos
Criterios de aceptación: POST /contacts - Verificará que la petición contenga los campos name y email
> OT222-72 - crud de contactos

- migrations/20220712022756-create-members.js
- models/members.js
COMO usuario administrador
QUIERO gestionar los Miembros de la ONG
PARA modificar los Miembros de la Organización
Criterios de aceptación:
Se podrán gestionar los Miembros de la ONG. Nombre de tabla: members. Campos: name, image
> OT222-88 -creación de modelo y migración de miembros

- controllers/activities.js
- Endpoint /activities/:id for update activity. Returns updated obj.
> Endpoint /activities/:id for update activity

- seeders/20220723133821-staff.js
** OT222-93 Seed added for staff members.
> seed for staff members

- controllers/users.js
- routes/middlewares/AdminAuth.js
- routes/users.js
- seeders/20201109013159-create-demo-user.js
- test/users.test.js
- /users endpoint test
- Truncate users table on seed:undo
- /users endpoint improved
- Status code changed to 401 if token is invalid in AdminAuth middleware
> Ot222-113 - /users endpoint test

- controllers/members.js
- routes/members.js
- seeders/20220723133821-demo-members.js
- test/members.test.js
- /members endpoint tests created
- demo-members seed now truncates ids
- /members endpoint improved
> Ot222-114 - /members endpoint test

- controllers/contacts.js
- seeders/20220722220801-demo-testimonials.js
- test/contacts.test.js
testing contacts y cambio seders Testimony
> testing contacts

- controllers/activities.js
- controllers/categories.js
- test/activities.test.js
*testing for endpoints /activities
> OT222-117 test endpoint /activities

- app.js
- docs/components.yml
- docs/swaggerDef.js
- package.json
- routes/docs.js
- Set up swagger with swagger-jsdoc.
> Swagger set up

- models/user.js
- routes/auth.js
Swagger docs added for user authentication and User model
> OT222-136 - Swagger docs added for user authentication
